- name: add redis extras on RHEL 8/9
  hosts: all
  become: true
  vars:
    ansible_install_dir: "{{ playbook_dir }}"
  tasks:
    - name: create script directory
      file:
        path: /redis/scripts
        state: directory
        mode: 0755
        owner: root
    - name: copy scripts,whls,rpms to server
      copy:
        src: "{{ item.path }}"
        dest: /redis/scripts
        force: no
        mode: 0755
      loop:
        - { path: "{{ playbook_dir }}/scripts/addMemory" }
        - { path: "{{ playbook_dir }}/scripts/Help" }
        - { path: "{{ playbook_dir }}/scripts/RedisCommon" }
        - { path: "{{ playbook_dir }}/scripts/RedisStatus" }
        - { path: "{{ playbook_dir }}/scripts/addMemory" }
        - { path: "{{ playbook_dir }}/scripts/RedisUpgrade" }
        - { path: "{{ playbook_dir }}/scripts/Sys" }
        - { path: "{{ playbook_dir }}/whls" }
        - { path: "{{ playbook_dir }}/rpms" }
    - name: install python 3.11 
      shell: yum install /redis/scripts/rpms/*.rpm --disablerepo="*" -y
    - name: install redis-python
      pip:
         name: redis-7.1.0-py3-none-any.whl
         executable: pip3.11
         chdir: /redis/scripts/whls      
    - name: install wcwidth
      pip:
         name: wcwidth-0.3.5-py3-none-any.whl
         executable: pip3.11
         chdir: /redis/scripts/whls 
    - name: install prettytable
      pip:
         name: prettytable-3.17.0-py3-none-any.whl
         executable: pip3.11
         chdir: /redis/scripts/whls 
    - name: add redis tools to bashrc
      blockinfile:
        path: /root/.bashrc
        block: | 
          PATH=$PATH:$HOME/bin
          export PATH
          alias sys='source /redis/scripts/Sys/sys.sh'
          alias status='python3.11 /redis/scripts/RedisStatus/status.py'
          alias addmemory='python3.11 /redis/scripts/addMemory/addRedisMemory.py'
          alias help='/redis/scripts/Help/help.sh'
        state: present




